"""baseline: full schema from models

Revision ID: 1ec2ff72f759
Revises: 
Create Date: 2026-07-14 20:53:04.362571

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1ec2ff72f759'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('repo', sa.String(length=200), nullable=False),
    sa.Column('provisioning', sa.String(length=12), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('initials', sa.String(length=4), nullable=False),
    sa.Column('hue', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('operator_app_mutes',
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('operator_id', 'app_id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('urgency', sa.String(length=8), nullable=False),
    sa.Column('reach', sa.String(length=120), nullable=True),
    sa.Column('impact_metric', sa.String(length=12), nullable=True),
    sa.Column('impact_value', sa.String(length=120), nullable=True),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('new_app_name', sa.String(length=120), nullable=True),
    sa.Column('bug_where', sa.String(length=200), nullable=True),
    sa.Column('extra_detail', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gate', sa.String(length=20), nullable=True),
    sa.Column('needs_human', sa.Boolean(), nullable=False),
    sa.Column('needs_human_reason', sa.String(length=300), nullable=True),
    sa.Column('reporter', sa.String(length=80), nullable=False),
    sa.Column('reporter_initials', sa.String(length=4), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('send_back_question', sa.Text(), nullable=True),
    sa.Column('send_back_response', sa.Text(), nullable=True),
    sa.Column('send_back_rounds', sa.Integer(), nullable=False),
    sa.Column('repo_ready', sa.Boolean(), nullable=False),
    sa.Column('spec_pr_open', sa.Boolean(), nullable=False),
    sa.Column('stage2_fired', sa.Boolean(), nullable=False),
    sa.Column('spec_open_note', sa.Text(), nullable=True),
    sa.Column('sim_step', sa.Integer(), nullable=False),
    sa.Column('pending_question', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('reopen_ceiling', sa.Integer(), nullable=True),
    sa.Column('prototype_html', sa.Text(), nullable=True),
    sa.Column('prototype_status', sa.String(length=10), nullable=False),
    sa.Column('stage_entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('stored', sa.String(length=72), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=80), nullable=False),
    sa.Column('initials', sa.String(length=4), nullable=False),
    sa.Column('color', sa.String(length=12), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('sub', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('bot', sa.Boolean(), nullable=False),
    sa.Column('broadcast', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_events_request_id'), 'progress_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_progress_events_subject_id'), 'progress_events', ['subject_id'], unique=False)
    op.create_table('prototype_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('annotation', sa.JSON(), nullable=True),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spec_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('prov', sa.String(length=20), nullable=True),
    sa.Column('assume', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spec_lines')
    op.drop_table('prototype_turns')
    op.drop_index(op.f('ix_progress_events_subject_id'), table_name='progress_events')
    op.drop_index(op.f('ix_progress_events_request_id'), table_name='progress_events')
    op.drop_table('progress_events')
    op.drop_table('interview_turns')
    op.drop_table('comments')
    op.drop_table('audit_events')
    op.drop_table('attachments')
    op.drop_table('requests')
    op.drop_table('operator_app_mutes')
    op.drop_table('operators')
    op.drop_table('apps')
    # ### end Alembic commands ###
