"""leader_epoch table

Revision ID: 893ac1fcca61
Revises: 1ec2ff72f759
Create Date: 2026-07-14 21:37:45.706248

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '893ac1fcca61'
down_revision: Union[str, Sequence[str], None] = '1ec2ff72f759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leader_epochs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("INSERT INTO leader_epochs (id, epoch) VALUES (1, 0)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leader_epochs')
    # ### end Alembic commands ###
