apiVersion: v1
kind: ConfigMap
metadata:
  name: factory-config
data:
  FACTORY_SEED_DEMO: "0"
  FACTORY_DB_URL: null
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factory-api
spec:
  template:
    spec:
      containers:
        - name: api
          env:
            - name: FACTORY_DB_URL
              valueFrom:
                secretKeyRef:
                  name: factory-db
                  key: url
